import { TransactionPageTableData } from "./TransactionPageTableConfig";

export default function useTransactionPageTableLogic(): TransactionPageTableData[] {
  return [
    {
      name: "Juan Perez / John Smith Smith Jr",
      transactionType: "Bank Transfer",
      transactionFee: "0.00",
      status: "completed",
      amount: "+454.00 CHF",
      timestamp: "11/06/2022",
      beId: 100000,
      icon: "bank-transfert",
    },
    {
      name: "John smith",
      transactionType: "QR Code Payment",
      transactionFee: "0.00",
      status: "Initiated",
      amount: "-330.00 GBP",
      timestamp: "11/06/2022",
      beId: 100000,
      icon: "qr",
    },
    {
      name: "John smith",
      transactionType: "Savings withdrawal",
      transactionFee: "0.00",
      status: "completed",
      amount: "-24.00 USD",
      timestamp: "11/06/2022",
      beId: 100000,
      icon: "saving-withdraw",
    },
    {
      name: "Juan Perez / John Smith Smith Jr",
      transactionType: "Bank Transfer",
      transactionFee: "0.00",
      status: "completed",
      amount: "+454.00 CHF",
      timestamp: "11/06/2022",
      beId: 100000,
      icon: "bank-transfert",
    },
    {
      name: "John smith",
      transactionType: "QR Code Payment",
      transactionFee: "0.00",
      status: "completed",
      amount: "-330.00 GBP",
      timestamp: "11/06/2022",
      beId: "00000",
      icon: "qr",
    },
    {
      name: "John smith",
      transactionType: "Savings withdrawal",
      transactionFee: "0.00",
      status: "Failed",
      amount: "-24.00 USD",
      timestamp: "11/06/2022",
      beId: "00000",
      icon: "saving-withdraw",
    },
    {
      name: "Juan Perez / John Smith Smith Jr",
      transactionType: "Bank Transfer",
      transactionFee: "0.00",
      status: "completed",
      amount: "+454.00 CHF",
      timestamp: "11/06/2022",
      beId: "00000",
      icon: "bank-transfert",
    },
    {
      name: "John smith",
      transactionType: "QR Code Payment",
      transactionFee: "0.00",
      status: "completed",
      amount: "-330.00 GBP",
      timestamp: "11/06/2022",
      beId: "00000",
      icon: "qr",
    },
    {
      name: "John smith",
      transactionType: "Savings withdrawal",
      transactionFee: "0.00",
      status: "completed",
      amount: "-24.00 USD",
      timestamp: "11/06/2022",
      beId: "00000",
      icon: "saving-withdraw",
    },
  ];
}
